//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 02:40:54 PM EDT 
//


package com.trustiphi.tpm2verification.platformcertparse;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.trustiphi.tpm2verification.platformcertparse
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlatformCertificateData }
     * 
     */
    public PlatformCertificateData createPlatformCertificateData() {
        return new PlatformCertificateData();
    }

    /**
     * Create an instance of {@link XmlCertificatePolicies }
     * 
     */
    public XmlCertificatePolicies createXmlCertificatePolicies() {
        return new XmlCertificatePolicies();
    }

    /**
     * Create an instance of {@link XmlGeneralName }
     * 
     */
    public XmlGeneralName createXmlGeneralName() {
        return new XmlGeneralName();
    }

    /**
     * Create an instance of {@link XmlCRLDistributionPoints }
     * 
     */
    public XmlCRLDistributionPoints createXmlCRLDistributionPoints() {
        return new XmlCRLDistributionPoints();
    }

    /**
     * Create an instance of {@link XmlCommonCriteriaMeasures }
     * 
     */
    public XmlCommonCriteriaMeasures createXmlCommonCriteriaMeasures() {
        return new XmlCommonCriteriaMeasures();
    }

    /**
     * Create an instance of {@link XmlURIReference }
     * 
     */
    public XmlURIReference createXmlURIReference() {
        return new XmlURIReference();
    }

    /**
     * Create an instance of {@link XmlComponentIdentifier }
     * 
     */
    public XmlComponentIdentifier createXmlComponentIdentifier() {
        return new XmlComponentIdentifier();
    }

    /**
     * Create an instance of {@link XmlProperties }
     * 
     */
    public XmlProperties createXmlProperties() {
        return new XmlProperties();
    }

    /**
     * Create an instance of {@link XmlDistributionPointName }
     * 
     */
    public XmlDistributionPointName createXmlDistributionPointName() {
        return new XmlDistributionPointName();
    }

    /**
     * Create an instance of {@link XmlPolicyQualifier }
     * 
     */
    public XmlPolicyQualifier createXmlPolicyQualifier() {
        return new XmlPolicyQualifier();
    }

    /**
     * Create an instance of {@link XmlComponentAddress }
     * 
     */
    public XmlComponentAddress createXmlComponentAddress() {
        return new XmlComponentAddress();
    }

}
