//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 02:40:54 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.trustiphi.com/platfromcertificateparser", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.trustiphi.tpm2verification.platformcertparse;
