//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 02:40:54 PM EDT 
//


package com.trustiphi.tpm2verification.platformcertparse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlCommonCriteriaMeasures complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlCommonCriteriaMeasures">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="assurancelevel" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;maxInclusive value="7"/>
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="evaluationStatus" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="plus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="strengthOfFunction" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="profileOid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="profileUri" type="{www.trustiphi.com/platfromcertificateparser}XmlURIReference" minOccurs="0"/>
 *         &lt;element name="targetOid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="targetUri" type="{www.trustiphi.com/platfromcertificateparser}XmlURIReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlCommonCriteriaMeasures", propOrder = {
    "version",
    "assurancelevel",
    "evaluationStatus",
    "plus",
    "strengthOfFunction",
    "profileOid",
    "profileUri",
    "targetOid",
    "targetUri"
})
public class XmlCommonCriteriaMeasures {

    protected String version;
    protected Integer assurancelevel;
    protected Integer evaluationStatus;
    protected Boolean plus;
    protected Integer strengthOfFunction;
    protected String profileOid;
    protected XmlURIReference profileUri;
    protected String targetOid;
    protected XmlURIReference targetUri;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the assurancelevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAssurancelevel() {
        return assurancelevel;
    }

    /**
     * Sets the value of the assurancelevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAssurancelevel(Integer value) {
        this.assurancelevel = value;
    }

    /**
     * Gets the value of the evaluationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEvaluationStatus() {
        return evaluationStatus;
    }

    /**
     * Sets the value of the evaluationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEvaluationStatus(Integer value) {
        this.evaluationStatus = value;
    }

    /**
     * Gets the value of the plus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPlus() {
        return plus;
    }

    /**
     * Sets the value of the plus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPlus(Boolean value) {
        this.plus = value;
    }

    /**
     * Gets the value of the strengthOfFunction property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStrengthOfFunction() {
        return strengthOfFunction;
    }

    /**
     * Sets the value of the strengthOfFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStrengthOfFunction(Integer value) {
        this.strengthOfFunction = value;
    }

    /**
     * Gets the value of the profileOid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileOid() {
        return profileOid;
    }

    /**
     * Sets the value of the profileOid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileOid(String value) {
        this.profileOid = value;
    }

    /**
     * Gets the value of the profileUri property.
     * 
     * @return
     *     possible object is
     *     {@link XmlURIReference }
     *     
     */
    public XmlURIReference getProfileUri() {
        return profileUri;
    }

    /**
     * Sets the value of the profileUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlURIReference }
     *     
     */
    public void setProfileUri(XmlURIReference value) {
        this.profileUri = value;
    }

    /**
     * Gets the value of the targetOid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetOid() {
        return targetOid;
    }

    /**
     * Sets the value of the targetOid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetOid(String value) {
        this.targetOid = value;
    }

    /**
     * Gets the value of the targetUri property.
     * 
     * @return
     *     possible object is
     *     {@link XmlURIReference }
     *     
     */
    public XmlURIReference getTargetUri() {
        return targetUri;
    }

    /**
     * Sets the value of the targetUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlURIReference }
     *     
     */
    public void setTargetUri(XmlURIReference value) {
        this.targetUri = value;
    }

}
