//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 02:40:54 PM EDT 
//


package com.trustiphi.tpm2verification.platformcertparse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlComponentIdentifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlComponentIdentifier">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="componentManufacturer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="componentModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="componentSerial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="componentRevision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="componentManufacturerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fieldReplaceable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="componentAddress" type="{www.trustiphi.com/platfromcertificateparser}XmlComponentAddress" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlComponentIdentifier", propOrder = {
    "componentManufacturer",
    "componentModel",
    "componentSerial",
    "componentRevision",
    "componentManufacturerId",
    "fieldReplaceable",
    "componentAddress"
})
public class XmlComponentIdentifier {

    @XmlElement(required = true)
    protected String componentManufacturer;
    @XmlElement(required = true)
    protected String componentModel;
    protected String componentSerial;
    protected String componentRevision;
    protected String componentManufacturerId;
    protected Boolean fieldReplaceable;
    protected List<XmlComponentAddress> componentAddress;

    /**
     * Gets the value of the componentManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentManufacturer() {
        return componentManufacturer;
    }

    /**
     * Sets the value of the componentManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentManufacturer(String value) {
        this.componentManufacturer = value;
    }

    /**
     * Gets the value of the componentModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentModel() {
        return componentModel;
    }

    /**
     * Sets the value of the componentModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentModel(String value) {
        this.componentModel = value;
    }

    /**
     * Gets the value of the componentSerial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentSerial() {
        return componentSerial;
    }

    /**
     * Sets the value of the componentSerial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentSerial(String value) {
        this.componentSerial = value;
    }

    /**
     * Gets the value of the componentRevision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentRevision() {
        return componentRevision;
    }

    /**
     * Sets the value of the componentRevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentRevision(String value) {
        this.componentRevision = value;
    }

    /**
     * Gets the value of the componentManufacturerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentManufacturerId() {
        return componentManufacturerId;
    }

    /**
     * Sets the value of the componentManufacturerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentManufacturerId(String value) {
        this.componentManufacturerId = value;
    }

    /**
     * Gets the value of the fieldReplaceable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFieldReplaceable() {
        return fieldReplaceable;
    }

    /**
     * Sets the value of the fieldReplaceable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFieldReplaceable(Boolean value) {
        this.fieldReplaceable = value;
    }

    /**
     * Gets the value of the componentAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the componentAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponentAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlComponentAddress }
     * 
     * 
     */
    public List<XmlComponentAddress> getComponentAddress() {
        if (componentAddress == null) {
            componentAddress = new ArrayList<XmlComponentAddress>();
        }
        return this.componentAddress;
    }

}
