//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 02:40:54 PM EDT 
//


package com.trustiphi.tpm2verification.platformcertparse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlCRLDistributionPoints complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlCRLDistributionPoints">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="distributionPoint" type="{www.trustiphi.com/platfromcertificateparser}XmlDistributionPointName" minOccurs="0"/>
 *         &lt;element name="reasons" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cRLIssuer" type="{www.trustiphi.com/platfromcertificateparser}XmlGeneralName" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlCRLDistributionPoints", propOrder = {
    "distributionPoint",
    "reasons",
    "crlIssuer"
})
public class XmlCRLDistributionPoints {

    protected XmlDistributionPointName distributionPoint;
    protected String reasons;
    @XmlElement(name = "cRLIssuer")
    protected XmlGeneralName crlIssuer;

    /**
     * Gets the value of the distributionPoint property.
     * 
     * @return
     *     possible object is
     *     {@link XmlDistributionPointName }
     *     
     */
    public XmlDistributionPointName getDistributionPoint() {
        return distributionPoint;
    }

    /**
     * Sets the value of the distributionPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlDistributionPointName }
     *     
     */
    public void setDistributionPoint(XmlDistributionPointName value) {
        this.distributionPoint = value;
    }

    /**
     * Gets the value of the reasons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasons() {
        return reasons;
    }

    /**
     * Sets the value of the reasons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasons(String value) {
        this.reasons = value;
    }

    /**
     * Gets the value of the crlIssuer property.
     * 
     * @return
     *     possible object is
     *     {@link XmlGeneralName }
     *     
     */
    public XmlGeneralName getCRLIssuer() {
        return crlIssuer;
    }

    /**
     * Sets the value of the crlIssuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlGeneralName }
     *     
     */
    public void setCRLIssuer(XmlGeneralName value) {
        this.crlIssuer = value;
    }

}
