//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 02:40:54 PM EDT 
//


package com.trustiphi.tpm2verification.platformcertparse;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlGeneralNameTag.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="XmlGeneralNameTag">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="otherName"/>
 *     &lt;enumeration value="rfc822Name"/>
 *     &lt;enumeration value="dNSName"/>
 *     &lt;enumeration value="x400Address"/>
 *     &lt;enumeration value="directoryName"/>
 *     &lt;enumeration value="ediPartyName"/>
 *     &lt;enumeration value="uniformResourceIdentifier"/>
 *     &lt;enumeration value="iPAddress"/>
 *     &lt;enumeration value="registeredID"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "XmlGeneralNameTag")
@XmlEnum
public enum XmlGeneralNameTag {

    @XmlEnumValue("otherName")
    OTHER_NAME("otherName"),
    @XmlEnumValue("rfc822Name")
    RFC_822_NAME("rfc822Name"),
    @XmlEnumValue("dNSName")
    D_NS_NAME("dNSName"),
    @XmlEnumValue("x400Address")
    X_400_ADDRESS("x400Address"),
    @XmlEnumValue("directoryName")
    DIRECTORY_NAME("directoryName"),
    @XmlEnumValue("ediPartyName")
    EDI_PARTY_NAME("ediPartyName"),
    @XmlEnumValue("uniformResourceIdentifier")
    UNIFORM_RESOURCE_IDENTIFIER("uniformResourceIdentifier"),
    @XmlEnumValue("iPAddress")
    I_P_ADDRESS("iPAddress"),
    @XmlEnumValue("registeredID")
    REGISTERED_ID("registeredID");
    private final String value;

    XmlGeneralNameTag(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static XmlGeneralNameTag fromValue(String v) {
        for (XmlGeneralNameTag c: XmlGeneralNameTag.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
