//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 02:40:54 PM EDT 
//


package com.trustiphi.tpm2verification.platformcertparse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlDistributionPointName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlDistributionPointName">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="fullname" type="{www.trustiphi.com/platfromcertificateparser}XmlGeneralName" maxOccurs="unbounded"/>
 *         &lt;element name="nameRelativeToCRLIssuer" type="{www.trustiphi.com/platfromcertificateparser}XmlGeneralName" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlDistributionPointName", propOrder = {
    "fullname",
    "nameRelativeToCRLIssuer"
})
public class XmlDistributionPointName {

    protected List<XmlGeneralName> fullname;
    protected List<XmlGeneralName> nameRelativeToCRLIssuer;

    /**
     * Gets the value of the fullname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fullname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFullname().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlGeneralName }
     * 
     * 
     */
    public List<XmlGeneralName> getFullname() {
        if (fullname == null) {
            fullname = new ArrayList<XmlGeneralName>();
        }
        return this.fullname;
    }

    /**
     * Gets the value of the nameRelativeToCRLIssuer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameRelativeToCRLIssuer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameRelativeToCRLIssuer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlGeneralName }
     * 
     * 
     */
    public List<XmlGeneralName> getNameRelativeToCRLIssuer() {
        if (nameRelativeToCRLIssuer == null) {
            nameRelativeToCRLIssuer = new ArrayList<XmlGeneralName>();
        }
        return this.nameRelativeToCRLIssuer;
    }

}
